/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package travel;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author tashf
 */
public class Chittagong extends javax.swing.JFrame {

    /**
     * Creates new form Chittagong
     */
    public Chittagong() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        icon_of_historical_place = new javax.swing.JLabel();
        Historical = new javax.swing.JButton();
        restaurent = new javax.swing.JButton();
        hotel = new javax.swing.JButton();
        icon_of_hotel = new javax.swing.JLabel();
        icon_of_restaurent = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        title.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        title.setForeground(new java.awt.Color(255, 255, 255));
        title.setText("CHITTAGONG");
        getContentPane().add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 50, 260, 50));

        jPanel1.setBackground(new java.awt.Color(255, 153, 153,65));

        icon_of_historical_place.setIcon(new javax.swing.ImageIcon(getClass().getResource("/travel/newpackage/hisyoPlace.jpg"))); // NOI18N

        Historical.setBackground(new java.awt.Color(255, 102, 102));
        Historical.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Historical.setForeground(new java.awt.Color(255, 255, 255));
        Historical.setText("Historical Places");
        Historical.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HistoricalActionPerformed(evt);
            }
        });

        restaurent.setBackground(new java.awt.Color(255, 102, 102));
        restaurent.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        restaurent.setForeground(new java.awt.Color(255, 255, 255));
        restaurent.setText("Restaurents");
        restaurent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restaurentActionPerformed(evt);
            }
        });

        hotel.setBackground(new java.awt.Color(255, 102, 102));
        hotel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        hotel.setForeground(new java.awt.Color(255, 255, 255));
        hotel.setText("Hotels");
        hotel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hotelActionPerformed(evt);
            }
        });

        icon_of_hotel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/travel/newpackage/icons8-hotel-building-100.png"))); // NOI18N

        icon_of_restaurent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/travel/newpackage/icons8-restaurant-100.png"))); // NOI18N

        back.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/travel/newpackage/icons8-back-64.png"))); // NOI18N
        back.setContentAreaFilled(false);
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(icon_of_historical_place, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(Historical, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(icon_of_restaurent)
                            .addComponent(icon_of_hotel, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hotel, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(restaurent, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(171, 171, 171)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(icon_of_historical_place)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(Historical, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(icon_of_restaurent))
                    .addComponent(icon_of_hotel)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(hotel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(restaurent, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addComponent(back)
                .addGap(72, 72, 72))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 680));

        jLabel1.setBackground(new java.awt.Color(255, 102, 102));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/travel/newpackage/ctgmap.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1180, 700));

        setSize(new java.awt.Dimension(1192, 730));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void HistoricalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HistoricalActionPerformed
        // TODO add your handling code here:
         this.setVisible(false);
        
            new ChittagongPlaces().setVisible(true);
        

    }//GEN-LAST:event_HistoricalActionPerformed

    private void hotelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hotelActionPerformed
        // TODO add your handling code here:
        
         this.setVisible(false);
        try {
            new hotelChittagong().setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(Chittagong.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_hotelActionPerformed

    private void restaurentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restaurentActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        try {
            new ChitRest().setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(Dhaka.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_restaurentActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:

        this.setVisible(false);
        new Menu().setVisible(true);

    }//GEN-LAST:event_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Chittagong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Chittagong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Chittagong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Chittagong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Chittagong().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Historical;
    private javax.swing.JButton back;
    private javax.swing.JButton hotel;
    private javax.swing.JLabel icon_of_historical_place;
    private javax.swing.JLabel icon_of_hotel;
    private javax.swing.JLabel icon_of_restaurent;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton restaurent;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
