/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package travel;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;


/**
 *
 * @author Asus
 */
public class Dhaka extends javax.swing.JFrame {

    /**
     * Creates new form Dhaka
     */
    public Dhaka() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        page3 = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        back = new javax.swing.JButton();
        icon_of_hotel1 = new javax.swing.JLabel();
        icon_of_histoPlace = new javax.swing.JLabel();
        icon_of_restru = new javax.swing.JLabel();
        Historical = new javax.swing.JButton();
        hotel = new javax.swing.JButton();
        restaurent = new javax.swing.JButton();
        page03 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(300, 100));
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(1200, 687));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        page3.setOpaque(false);

        title.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        title.setText("Dhaka");

        jPanel1.setBackground(new java.awt.Color(51, 153, 255,80));

        back.setBackground(new java.awt.Color(51, 0, 51));
        back.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        back.setForeground(new java.awt.Color(255, 255, 255));
        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/travel/newpackage/icons8-back-64.png"))); // NOI18N
        back.setContentAreaFilled(false);
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        icon_of_hotel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/travel/newpackage/icons8-hotel-building-100.png"))); // NOI18N

        icon_of_histoPlace.setIcon(new javax.swing.ImageIcon(getClass().getResource("/travel/newpackage/hisyoPlace.jpg"))); // NOI18N
        icon_of_histoPlace.setText("jLabel1");

        icon_of_restru.setIcon(new javax.swing.ImageIcon(getClass().getResource("/travel/newpackage/icons8-restaurant-100.png"))); // NOI18N
        icon_of_restru.setText("jLabel1");

        Historical.setBackground(new java.awt.Color(51, 0, 51));
        Historical.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Historical.setForeground(new java.awt.Color(255, 255, 255));
        Historical.setText("Historical Places");
        Historical.setMaximumSize(new java.awt.Dimension(67, 27));
        Historical.setMinimumSize(new java.awt.Dimension(67, 27));
        Historical.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HistoricalActionPerformed(evt);
            }
        });

        hotel.setBackground(new java.awt.Color(51, 0, 51));
        hotel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        hotel.setForeground(new java.awt.Color(255, 255, 255));
        hotel.setText("Hotels");
        hotel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hotelActionPerformed(evt);
            }
        });

        restaurent.setBackground(new java.awt.Color(51, 0, 51));
        restaurent.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        restaurent.setForeground(new java.awt.Color(255, 255, 255));
        restaurent.setText("Restaurents");
        restaurent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restaurentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(icon_of_hotel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(restaurent, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(icon_of_restru, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(icon_of_histoPlace, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hotel, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Historical, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(187, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(icon_of_histoPlace)
                    .addComponent(Historical, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(icon_of_restru)
                            .addComponent(hotel, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(restaurent, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17))
                    .addComponent(icon_of_hotel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(93, 93, 93)
                .addComponent(back)
                .addGap(105, 105, 105))
        );

        javax.swing.GroupLayout page3Layout = new javax.swing.GroupLayout(page3);
        page3.setLayout(page3Layout);
        page3Layout.setHorizontalGroup(
            page3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(page3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(524, Short.MAX_VALUE))
        );
        page3Layout.setVerticalGroup(
            page3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(page3Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(page3Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(page3, gridBagConstraints);

        page03.setIcon(new javax.swing.ImageIcon(getClass().getResource("/travel/newpackage/dmap (1).jpg"))); // NOI18N
        page03.setName(""); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(page03, gridBagConstraints);

        setSize(new java.awt.Dimension(1218, 761));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void HistoricalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HistoricalActionPerformed
        // TODO add your handling code here:
        
        this.setVisible(false);
        
            new DhakaPlaces().setVisible(true);
       
    }//GEN-LAST:event_HistoricalActionPerformed

    private void hotelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hotelActionPerformed
        // TODO add your handling code here:
         
         this.setVisible(false);
        try {
            new HotelDhaka().setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(Dhaka.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_hotelActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        
        this.setVisible(false);
        new Menu().setVisible(true);
        
    }//GEN-LAST:event_backActionPerformed

    private void restaurentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restaurentActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        try {
            new DhakaRest().setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(Dhaka.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_restaurentActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dhaka.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dhaka.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dhaka.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dhaka.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dhaka().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Historical;
    private javax.swing.JButton back;
    private javax.swing.JButton hotel;
    private javax.swing.JLabel icon_of_histoPlace;
    private javax.swing.JLabel icon_of_hotel1;
    private javax.swing.JLabel icon_of_restru;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel page03;
    private javax.swing.JPanel page3;
    private javax.swing.JButton restaurent;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
