/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package travel;

import java.awt.Color;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author tashf
 */
public class Khulna extends javax.swing.JFrame {

    /**
     * Creates new form Khulna
     */
    public Khulna() {
        initComponents();
        
        tt.setBackground(new Color(255,153,153,150));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        hotel1 = new javax.swing.JButton();
        icon_of_hotel2 = new javax.swing.JLabel();
        icon_of_histoPlace1 = new javax.swing.JLabel();
        Historical1 = new javax.swing.JButton();
        restaurent1 = new javax.swing.JButton();
        icon_of_restru1 = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        tt = new javax.swing.JLabel();
        page05 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));
        setLocationByPlatform(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        hotel1.setBackground(new java.awt.Color(0, 102, 153));
        hotel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        hotel1.setForeground(new java.awt.Color(255, 255, 255));
        hotel1.setText("Hotels");
        hotel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hotel1ActionPerformed(evt);
            }
        });
        getContentPane().add(hotel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 360, 130, 50));

        icon_of_hotel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/travel/newpackage/icons8-hotel-building-100.png"))); // NOI18N
        getContentPane().add(icon_of_hotel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, -1, -1));

        icon_of_histoPlace1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/travel/newpackage/hisyoPlace.jpg"))); // NOI18N
        getContentPane().add(icon_of_histoPlace1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, -1, -1));

        Historical1.setBackground(new java.awt.Color(0, 102, 153));
        Historical1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Historical1.setForeground(new java.awt.Color(255, 255, 255));
        Historical1.setText("Historical Places");
        Historical1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Historical1ActionPerformed(evt);
            }
        });
        getContentPane().add(Historical1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 130, 50));

        restaurent1.setBackground(new java.awt.Color(0, 102, 153));
        restaurent1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        restaurent1.setForeground(new java.awt.Color(255, 255, 255));
        restaurent1.setText("Restaurents");
        restaurent1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restaurent1ActionPerformed(evt);
            }
        });
        getContentPane().add(restaurent1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, 130, 50));

        icon_of_restru1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/travel/newpackage/icons8-restaurant-100.png"))); // NOI18N
        getContentPane().add(icon_of_restru1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 100, 80));

        back.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/travel/newpackage/icons8-back-64.png"))); // NOI18N
        back.setContentAreaFilled(false);
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 540, 120, 80));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Khulna");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 86, 190, 40));

        tt.setBackground(new java.awt.Color(255, 153, 153));
        tt.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        tt.setForeground(new java.awt.Color(255, 255, 255));
        tt.setOpaque(true);
        getContentPane().add(tt, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 690));

        page05.setBackground(new java.awt.Color(255, 153, 153));
        page05.setIcon(new javax.swing.ImageIcon(getClass().getResource("/travel/newpackage/khulna-map (1).jpg"))); // NOI18N
        page05.setPreferredSize(new java.awt.Dimension(1200, 687));
        getContentPane().add(page05, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:

        this.setVisible(false);
        new Menu().setVisible(true);

    }//GEN-LAST:event_backActionPerformed

    private void Historical1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Historical1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        
            new KhulnaPlaces().setVisible(true);
        
    }//GEN-LAST:event_Historical1ActionPerformed

    private void hotel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hotel1ActionPerformed
        // TODO add your handling code here: this.setVisible(false);
      this.setVisible(false);
        try {
            new hotelKhulna().setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(Khulna.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_hotel1ActionPerformed

    private void restaurent1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restaurent1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        try {
            new KhulRest().setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(Khulna.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_restaurent1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Khulna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Khulna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Khulna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Khulna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Khulna().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Historical1;
    private javax.swing.JButton back;
    private javax.swing.JButton hotel1;
    private javax.swing.JLabel icon_of_histoPlace1;
    private javax.swing.JLabel icon_of_hotel2;
    private javax.swing.JLabel icon_of_restru1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel page05;
    private javax.swing.JButton restaurent1;
    private javax.swing.JLabel tt;
    // End of variables declaration//GEN-END:variables
}
