/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package travel;

import java.awt.Color;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Asus
 */
public class Rajshahi extends javax.swing.JFrame {

    /**
     * Creates new form Rajshahi
     */
    public Rajshahi() {
        initComponents();
        
        // tr.setBackground(new Color(102,255,253,100));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        back = new javax.swing.JButton();
        restaurent = new javax.swing.JButton();
        icon_of_restru = new javax.swing.JLabel();
        icon_of_histoPlace = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        hotel = new javax.swing.JButton();
        Historical = new javax.swing.JButton();
        icon_of_hotel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));
        setLocationByPlatform(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        back.setBackground(new java.awt.Color(255, 102, 0));
        back.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        back.setForeground(java.awt.Color.white);
        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/travel/newpackage/icons8-back-64.png"))); // NOI18N
        back.setContentAreaFilled(false);
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel1.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 520, -1, -1));

        restaurent.setBackground(new java.awt.Color(51, 0, 153));
        restaurent.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        restaurent.setForeground(new java.awt.Color(255, 255, 255));
        restaurent.setText("Restaurents");
        restaurent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restaurentActionPerformed(evt);
            }
        });
        jPanel1.add(restaurent, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 370, 140, 50));

        icon_of_restru.setIcon(new javax.swing.ImageIcon(getClass().getResource("/travel/newpackage/icons8-restaurant-100.png"))); // NOI18N
        icon_of_restru.setText("jLabel1");
        jPanel1.add(icon_of_restru, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 350, 100, -1));

        icon_of_histoPlace.setIcon(new javax.swing.ImageIcon(getClass().getResource("/travel/newpackage/hisyoPlace.jpg"))); // NOI18N
        icon_of_histoPlace.setText("jLabel1");
        jPanel1.add(icon_of_histoPlace, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 80, -1));

        jLabel3.setFont(new java.awt.Font("Tw Cen MT", 3, 36)); // NOI18N
        jLabel3.setText("RAJSHAHI");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 240, 70));

        jPanel2.setBackground(new java.awt.Color(51, 255, 204,80));

        hotel.setBackground(new java.awt.Color(51, 0, 153));
        hotel.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        hotel.setForeground(new java.awt.Color(255, 255, 255));
        hotel.setText("Hotels");
        hotel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hotelActionPerformed(evt);
            }
        });

        Historical.setBackground(new java.awt.Color(51, 0, 153));
        Historical.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        Historical.setForeground(new java.awt.Color(255, 255, 255));
        Historical.setText("Historical Places");
        Historical.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HistoricalActionPerformed(evt);
            }
        });

        icon_of_hotel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/travel/newpackage/icons8-hotel-building-100.png"))); // NOI18N
        icon_of_hotel1.setText("jLabel1");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(86, Short.MAX_VALUE)
                .addComponent(icon_of_hotel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Historical, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hotel, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(207, 207, 207)
                .addComponent(Historical, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hotel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(icon_of_hotel1))
                .addContainerGap(324, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 690));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/travel/newpackage/rajshahi-04.jpg"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1198, 682));

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(1200, 729));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void HistoricalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HistoricalActionPerformed
        // TODO add your handling code here:
          this.setVisible(false);
        
            new RajshahiPlaces().setVisible(true);
    }//GEN-LAST:event_HistoricalActionPerformed

    private void hotelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hotelActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        try {
            new hotelRaj().setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(Rajshahi.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_hotelActionPerformed

    private void restaurentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restaurentActionPerformed
        // TODO add your handling code here:
         this.setVisible(false);
        try {
            new RajRest().setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(Rajshahi.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_restaurentActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
         this.setVisible(false);
         new Menu().setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Rajshahi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Rajshahi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Rajshahi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Rajshahi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Rajshahi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Historical;
    private javax.swing.JButton back;
    private javax.swing.JButton hotel;
    private javax.swing.JLabel icon_of_histoPlace;
    private javax.swing.JLabel icon_of_hotel1;
    private javax.swing.JLabel icon_of_restru;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton restaurent;
    // End of variables declaration//GEN-END:variables
}
